<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/proto/passport.proto

namespace USC\Passport;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>passport.DeviceInfo</code>
 */
class DeviceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     */
    protected $ip = '';
    /**
     * Generated from protobuf field <code>string os = 2;</code>
     */
    protected $os = '';
    /**
     * Generated from protobuf field <code>string platform = 3;</code>
     */
    protected $platform = '';
    /**
     * Generated from protobuf field <code>string browser = 4;</code>
     */
    protected $browser = '';
    /**
     * Generated from protobuf field <code>string engine = 5;</code>
     */
    protected $engine = '';
    /**
     * Generated from protobuf field <code>bool is_bot = 6;</code>
     */
    protected $is_bot = false;
    /**
     * Generated from protobuf field <code>string locale = 7;</code>
     */
    protected $locale = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip
     *     @type string $os
     *     @type string $platform
     *     @type string $browser
     *     @type string $engine
     *     @type bool $is_bot
     *     @type string $locale
     * }
     */
    public function __construct($data = NULL) {
        \USC\Passport\Metadata\Passport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string os = 2;</code>
     * @return string
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * Generated from protobuf field <code>string os = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkString($var, True);
        $this->os = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform = 3;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string browser = 4;</code>
     * @return string
     */
    public function getBrowser()
    {
        return $this->browser;
    }

    /**
     * Generated from protobuf field <code>string browser = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBrowser($var)
    {
        GPBUtil::checkString($var, True);
        $this->browser = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string engine = 5;</code>
     * @return string
     */
    public function getEngine()
    {
        return $this->engine;
    }

    /**
     * Generated from protobuf field <code>string engine = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEngine($var)
    {
        GPBUtil::checkString($var, True);
        $this->engine = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_bot = 6;</code>
     * @return bool
     */
    public function getIsBot()
    {
        return $this->is_bot;
    }

    /**
     * Generated from protobuf field <code>bool is_bot = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBot($var)
    {
        GPBUtil::checkBool($var);
        $this->is_bot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string locale = 7;</code>
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * Generated from protobuf field <code>string locale = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;

        return $this;
    }

}

