<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/proto/passport.proto

namespace USC\Passport;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>passport.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string originator = 1;</code>
     */
    protected $originator = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $originator
     * }
     */
    public function __construct($data = NULL) {
        \USC\Passport\Metadata\Passport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string originator = 1;</code>
     * @return string
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>string originator = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkString($var, True);
        $this->originator = $var;

        return $this;
    }

}

