<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/proto/passport.proto

namespace USC\Passport;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>passport.Integrity</code>
 */
class Integrity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>string key_name = 2;</code>
     */
    protected $key_name = '';
    /**
     * Generated from protobuf field <code>bytes hmac = 3;</code>
     */
    protected $hmac = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $key_name
     *     @type string $hmac
     * }
     */
    public function __construct($data = NULL) {
        \USC\Passport\Metadata\Passport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_name = 2;</code>
     * @return string
     */
    public function getKeyName()
    {
        return $this->key_name;
    }

    /**
     * Generated from protobuf field <code>string key_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hmac = 3;</code>
     * @return string
     */
    public function getHmac()
    {
        return $this->hmac;
    }

    /**
     * Generated from protobuf field <code>bytes hmac = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHmac($var)
    {
        GPBUtil::checkString($var, False);
        $this->hmac = $var;

        return $this;
    }

}

