<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/proto/passport.proto

namespace USC\Passport;

use UnexpectedValueException;

/**
 * Protobuf type <code>passport.PassportAuthenticationLevel</code>
 */
class PassportAuthenticationLevel
{
    /**
     * untrusted transport
     *
     * Generated from protobuf enum <code>LOW = 0;</code>
     */
    const LOW = 0;
    /**
     * secure tokens over TLS
     *
     * Generated from protobuf enum <code>HIGH = 1;</code>
     */
    const HIGH = 1;
    /**
     * MSL or user credentials
     *
     * Generated from protobuf enum <code>HIGHEST = 2;</code>
     */
    const HIGHEST = 2;

    private static $valueToName = [
        self::LOW => 'LOW',
        self::HIGH => 'HIGH',
        self::HIGHEST => 'HIGHEST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

