<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/proto/passport.proto

namespace USC\Passport;

use UnexpectedValueException;

/**
 * Protobuf type <code>passport.Source</code>
 */
class Source
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>COOKIE = 1;</code>
     */
    const COOKIE = 1;
    /**
     * Generated from protobuf enum <code>COOKIE_INSECURE = 2;</code>
     */
    const COOKIE_INSECURE = 2;
    /**
     * Generated from protobuf enum <code>JWT = 3;</code>
     */
    const JWT = 3;
    /**
     * Generated from protobuf enum <code>PARTNER_TOKEN = 4;</code>
     */
    const PARTNER_TOKEN = 4;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::COOKIE => 'COOKIE',
        self::COOKIE_INSECURE => 'COOKIE_INSECURE',
        self::JWT => 'JWT',
        self::PARTNER_TOKEN => 'PARTNER_TOKEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

